### ISSUE TITLE
MT4 version

### ISSUE THREAD

**Issue by Froousty** [nguemechieu/TelegramSignalTrader#2]
Hi,
I would like to test your solution and i tryed to use it with the actual files on MT4. And MT4 cannot load .mql5 extension.
Do you have this solution for MT4 version ?

And do you have more explanation about how to install correctly the files ?

**Comment by nguemechieu** [comment]
Hi. Thanks you for contacting me. The solution work and it is available for mt4 and mt5

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Froousty ***@***.***>
Sent: Tuesday, June 13, 2023 4:25:12 PM
To: nguemechieu/TelegramSignalTrader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nguemechieu/TelegramSignalTrader] MT4 version (Issue #2)


Hi,
I would like to test your solution and i tryed to use it with the actual files on MT4. And MT4 cannot load .mql5 extension.
Do you have this solution for MT4 version ?

And do you have more explanation about how to install correctly the files ?

**Comment by Froousty** [comment]
When I open the MT4 folder all the files are with .mql5 and .ex5 extensions.
When I open mt4 logiciel, I see nothing in EA, … anywhere 
So can you tell me how I can setup and start the process please ?
