### ISSUE TITLE
Execution Telegram Copier

### ISSUE THREAD

**Issue by Froousty** [nguemechieu/TelegramSignalTrader#4]
Hi,
thank you for updating your post. I have successfully run TelegramCopier.ex4 and mql4 on MT4. The telegram bot connects correctly :)
Another problem on my side, I'm trying to understand the last explanations you provided at the bottom of your post to run Telegram copy but I don't understand at all. Do you have any suggestions for clarification? Use a website, software or something else? I tried to run it via Pycharm but it doesn't work. It can't find Telegram Copier.

Can you please enlighten me?

**Comment by nguemechieu** [comment]
The bot uses key word such as EURUSD OR ANY AS CURRENCY PAIRS he found to set currency and
Buy or sell to open orders

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Froousty ***@***.***>
Sent: Wednesday, June 14, 2023 2:47:15 PM
To: nguemechieu/TelegramSignalTrader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nguemechieu/TelegramSignalTrader] Execution Telegram Copier (Issue #4)


Hi,
thank you for updating your post. I have successfully run TelegramCopier.ex4 and mql4 on MT4. The telegram bot connects correctly :)
Another problem on my side, I'm trying to understand the last explanations you provided at the bottom of your post to run Telegram copy but I don't understand at all. Do you have any suggestions for clarification? Use a website, software or something else? I tried to run it via Pycharm but it doesn't work. It can't find Telegram Copier.

Can you please enlighten me?

**Comment by nguemechieu** [comment]
To trade with limit orders or stop loss orders or market order you can set up in parameters .


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Froousty** [comment]
Currently I just attach the EA to a graph and connect my Telegram Bot.
When I click on the different buttons in the bot telegram nothing happens.
When I send this in the channel but nothing happens : 
BUY EURUSD
TP 1.084
SL 1.082

Do I need to do anything more for this to work?

**Comment by Froousty** [comment]
I've understood all the parameters on MT4 in the EA, it's quite intuitive but the operation between telegram and MT4 is not yet done... do you have an idea?

**Comment by nguemechieu** [comment]
This project is designed for mt4 and mt5 only not python or any other language.

**Comment by nguemechieu** [comment]
You should add the bot to the channel or chat group make sure your chat Id is well set . I will provide the the architecture of telegram group for better understanding once I have a chance


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Froousty** [comment]
Yeah understood. It doesn't work on my side.
The link from Telegram to MT4 doesn't work. I don't know if I'm using the right signal format, but yeah, I just don't get it.

**Comment by nguemechieu** [comment]
New update and bug fixed everything are now running . Click on demo to see youtube test
